name: example
description: A Flux Form Example

publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.8

  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1

  flux_form:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true