name: flux_form
description: >-
  A type-safe, rule-based form state management library. Features composition-based validation, 
  dynamic list support, sanitization, and smart UI state handling.
version: 0.1.0

repository: https://github.com/puntbyte/flux_form

topics:
  - form
  - validation
  - state-management
  - input
  - sanitization

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.26.0
  very_good_analysis: ^10.0.0