name: flux_form
description: >-
  A modular, type-safe form state management library. Features FormGroup aggregation, built-in 
  validators, sanitization pipelines, and smart UI error handling.
version: 0.3.0

repository: https://github.com/puntbyte/flux_form
homepage: https://github.com/puntbyte/flux_form
issue_tracker: https://github.com/puntbyte/flux_form/issues

topics:
  - form
  - validation
  - state-management
  - sanitization
  - productivity

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.26.0
  very_good_analysis: ^10.0.0