name: flux_form
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.26.0
  very_good_analysis: ^10.0.0
